/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegoppt;

/**
 *
 * @author alexc
 */
public class Game extends javax.swing.JFrame {

    private static int mano,manoRival,ganadas,perdidas,empates;
    
    /**
     * Creates new form Game
     */
    public Game() {
        this.mano=0;
        this.manoRival=0;
        this.ganadas=0;
        this.perdidas=0;
        this.empates=0;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbGame = new javax.swing.JLabel();
        btnPapel = new javax.swing.JButton();
        btnTijeras = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbJugador = new javax.swing.JLabel();
        lbRival = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPiedra = new javax.swing.JButton();
        lbEmpates = new javax.swing.JLabel();
        lbGanadas = new javax.swing.JLabel();
        lbPerdidas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lbGame.setBackground(new java.awt.Color(255, 204, 204));
        lbGame.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        lbGame.setForeground(new java.awt.Color(102, 0, 102));
        lbGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGame.setText("GAME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbGame, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbGame, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnPapel.setBackground(new java.awt.Color(153, 172, 255));
        btnPapel.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        btnPapel.setText("Papel");
        btnPapel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapelActionPerformed(evt);
            }
        });

        btnTijeras.setBackground(new java.awt.Color(153, 172, 255));
        btnTijeras.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        btnTijeras.setText("Tijeras");
        btnTijeras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTijeras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTijerasActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 171, 220));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbJugador.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbJugador.setForeground(new java.awt.Color(128, 126, 213));
        lbJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbRival.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbRival.setForeground(new java.awt.Color(128, 126, 213));
        lbRival.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lbJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(lbRival, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRival, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnPiedra.setBackground(new java.awt.Color(153, 172, 255));
        btnPiedra.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        btnPiedra.setText("Piedra");
        btnPiedra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPiedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiedraActionPerformed(evt);
            }
        });

        lbEmpates.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        lbEmpates.setForeground(new java.awt.Color(222, 81, 135));
        lbEmpates.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbEmpates.setText("Empates: 0");
        lbEmpates.setToolTipText("");

        lbGanadas.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        lbGanadas.setForeground(new java.awt.Color(222, 81, 135));
        lbGanadas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbGanadas.setText("Ganadas: 0");
        lbGanadas.setToolTipText("");

        lbPerdidas.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        lbPerdidas.setForeground(new java.awt.Color(222, 81, 135));
        lbPerdidas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPerdidas.setText("Perdidas: 0");
        lbPerdidas.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPiedra, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(lbGanadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmpates, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTijeras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPerdidas, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmpates, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGanadas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTijeras, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiedraActionPerformed
        // TODO add your handling code here:
        mano=1;
        jugada();
    }//GEN-LAST:event_btnPiedraActionPerformed

    private void btnPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapelActionPerformed
        // TODO add your handling code here:
        mano=2;
        jugada();
    }//GEN-LAST:event_btnPapelActionPerformed

    private void btnTijerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTijerasActionPerformed
        // TODO add your handling code here:
        mano=3;
        jugada();
    }//GEN-LAST:event_btnTijerasActionPerformed

    
    private void jugada(){
        manoRival = (int)(Math.random()*3+1);
        switch(mano){
            case 1:
                lbJugador.setText("Piedra"); // 1
                switch(manoRival){
                    case 1:
                        lbRival.setText("Piedra");
                        lbGame.setText("Empate");
                        empates++;
                    break;
                    case 2:
                        lbRival.setText("Papel");
                        lbGame.setText("Perdiste");
                        perdidas++;
                    break;
                    case 3:
                        lbRival.setText("Tijeras");
                        lbGame.setText("Ganaste");
                        ganadas++;
                    break;
                }
            break;
            case 2:
                lbJugador.setText("Papel"); // 2
                switch(manoRival){
                    case 1:
                        lbRival.setText("Piedra");
                        lbGame.setText("Ganaste");
                        ganadas++;
                    break;
                    case 2:
                        lbRival.setText("Papel");
                        lbGame.setText("Empate");
                        empates++;
                    break;
                    case 3:
                        lbRival.setText("Tijeras");
                        lbGame.setText("Perdiste");
                        perdidas++;
                    break;
                }
            break;
            case 3:
                lbJugador.setText("Tijeras"); // 3
                switch(manoRival){
                    case 1:
                        lbRival.setText("Piedra");
                        lbGame.setText("Perdiste");
                        perdidas++;
                    break;
                    case 2:
                        lbRival.setText("Papel");
                        lbGame.setText("Ganaste");
                        ganadas++;
                    break;
                    case 3:
                        lbRival.setText("Tijeras");
                        lbGame.setText("Empate");
                        empates++;
                    break;
                }
            break;
        }
        
        actualiza();
    }
    
    private void actualiza(){
        lbGanadas.setText("Ganadas: "+ganadas);
        lbPerdidas.setText("Perdidas: "+perdidas);
        lbEmpates.setText("Empates: "+empates);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPapel;
    private javax.swing.JButton btnPiedra;
    private javax.swing.JButton btnTijeras;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbEmpates;
    private javax.swing.JLabel lbGame;
    private javax.swing.JLabel lbGanadas;
    private javax.swing.JLabel lbJugador;
    private javax.swing.JLabel lbPerdidas;
    private javax.swing.JLabel lbRival;
    // End of variables declaration//GEN-END:variables
}
